# screen
# SCREEN = WIDTH, HEIGHT = 1200, 900
SCREEN = WIDTH, HEIGHT = 1920, 1080
CENTER = H_WIDTH, H_HEIGHT = WIDTH // 2, HEIGHT // 2

# canvas
GRID_SIZE = 32

# info panel
INFO_PANEL_SIZE = (H_WIDTH - 20, 40)
INFO_PANEL_POS = (H_WIDTH, HEIGHT - 30)

# items panel
ITEMS_PANEL_SIZE = (H_WIDTH // 2 - 24, HEIGHT - 50)
ITEMS_PANEL_POS = (H_WIDTH // 4, H_HEIGHT + 15)
ITEMS_IN_ROW = (ITEMS_PANEL_SIZE[0] - 40) // GRID_SIZE

# colors
BG = (5, 5, 5)
FPS_COLOR = 'skyblue'
GRID_COLOR = (30, 30, 30)
ORIGIN_COLOR = (0, 60, 0)
SELECTOR_COLOR = 'orange'
